DELETE FROM CITATION WHERE REF_ID NOT IN (SELECT PUB_ID FROM PUBLICATION);

ALTER TABLE `AP_DATA`.`AUTHOR_PUB` 
ADD INDEX `PUB_idx` (`PUB_ID` ASC);
ALTER TABLE `AP_DATA`.`AUTHOR_PUB` 
ADD CONSTRAINT `AUTHOR`
  FOREIGN KEY (`AUTHOR_ID`)
  REFERENCES `AP_DATA`.`AUTHOR` (`AUTHOR_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `PUB`
  FOREIGN KEY (`PUB_ID`)
  REFERENCES `AP_DATA`.`PUBLICATION` (`PUB_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
ALTER TABLE `AP_DATA`.`CITATION` 
ADD INDEX `REFERENCE_idx` (`REF_ID` ASC);
ALTER TABLE `AP_DATA`.`CITATION` 
ADD CONSTRAINT `PUBLICATION`
  FOREIGN KEY (`PUB_ID`)
  REFERENCES `AP_DATA`.`PUBLICATION` (`PUB_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `REFERENCE`
  FOREIGN KEY (`REF_ID`)
  REFERENCES `AP_DATA`.`PUBLICATION` (`PUB_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;