CREATE TABLE `PUBLICATION` (
  `PUB_ID` int(11) NOT NULL,
  `YEAR` int(11) DEFAULT NULL,
  `TITLE` varchar(510) DEFAULT NULL,
  `ABSTRACT` blob,
  `VENUE` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`PUB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `AUTHOR` (
  `AUTHOR_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(110) DEFAULT NULL,
  PRIMARY KEY (`AUTHOR_ID`),
  UNIQUE KEY `NAME_UNIQUE` (`NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=1444443 DEFAULT CHARSET=utf8;

CREATE TABLE `AUTHOR_PUB` (
  `AUTHOR_ID` int(11) NOT NULL,
  `PUB_ID` int(11) NOT NULL,
  PRIMARY KEY (`AUTHOR_ID`,`PUB_ID`),
  KEY `FOREIGN_AU_ID_idx` (`AUTHOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CITATION` (
  `PUB_ID` int(11) NOT NULL,
  `REF_ID` int(11) NOT NULL,
  PRIMARY KEY (`PUB_ID`,`REF_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
